// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1/recipes_api.proto

package com.recipes.api;

/**
 * Protobuf type {@code api.v1.GetRecipesByAuthorResponse}
 */
public final class GetRecipesByAuthorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.v1.GetRecipesByAuthorResponse)
    GetRecipesByAuthorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRecipesByAuthorResponse.newBuilder() to construct.
  private GetRecipesByAuthorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRecipesByAuthorResponse() {
    recipes_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRecipesByAuthorResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetRecipesByAuthorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              recipes_ = new java.util.ArrayList<com.recipes.model.Recipe>();
              mutable_bitField0_ |= 0x00000001;
            }
            recipes_.add(
                input.readMessage(com.recipes.model.Recipe.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        recipes_ = java.util.Collections.unmodifiableList(recipes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.recipes.api.GetRecipesByAuthorResponse.class, com.recipes.api.GetRecipesByAuthorResponse.Builder.class);
  }

  public static final int RECIPES_FIELD_NUMBER = 1;
  private java.util.List<com.recipes.model.Recipe> recipes_;
  /**
   * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
   */
  @java.lang.Override
  public java.util.List<com.recipes.model.Recipe> getRecipesList() {
    return recipes_;
  }
  /**
   * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.recipes.model.RecipeOrBuilder> 
      getRecipesOrBuilderList() {
    return recipes_;
  }
  /**
   * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
   */
  @java.lang.Override
  public int getRecipesCount() {
    return recipes_.size();
  }
  /**
   * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
   */
  @java.lang.Override
  public com.recipes.model.Recipe getRecipes(int index) {
    return recipes_.get(index);
  }
  /**
   * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
   */
  @java.lang.Override
  public com.recipes.model.RecipeOrBuilder getRecipesOrBuilder(
      int index) {
    return recipes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recipes_.size(); i++) {
      output.writeMessage(1, recipes_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < recipes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recipes_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.recipes.api.GetRecipesByAuthorResponse)) {
      return super.equals(obj);
    }
    com.recipes.api.GetRecipesByAuthorResponse other = (com.recipes.api.GetRecipesByAuthorResponse) obj;

    if (!getRecipesList()
        .equals(other.getRecipesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecipesCount() > 0) {
      hash = (37 * hash) + RECIPES_FIELD_NUMBER;
      hash = (53 * hash) + getRecipesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.recipes.api.GetRecipesByAuthorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v1.GetRecipesByAuthorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.GetRecipesByAuthorResponse)
      com.recipes.api.GetRecipesByAuthorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.recipes.api.GetRecipesByAuthorResponse.class, com.recipes.api.GetRecipesByAuthorResponse.Builder.class);
    }

    // Construct using com.recipes.api.GetRecipesByAuthorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecipesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (recipesBuilder_ == null) {
        recipes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recipesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorResponse_descriptor;
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorResponse getDefaultInstanceForType() {
      return com.recipes.api.GetRecipesByAuthorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorResponse build() {
      com.recipes.api.GetRecipesByAuthorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorResponse buildPartial() {
      com.recipes.api.GetRecipesByAuthorResponse result = new com.recipes.api.GetRecipesByAuthorResponse(this);
      int from_bitField0_ = bitField0_;
      if (recipesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recipes_ = java.util.Collections.unmodifiableList(recipes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recipes_ = recipes_;
      } else {
        result.recipes_ = recipesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.recipes.api.GetRecipesByAuthorResponse) {
        return mergeFrom((com.recipes.api.GetRecipesByAuthorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.recipes.api.GetRecipesByAuthorResponse other) {
      if (other == com.recipes.api.GetRecipesByAuthorResponse.getDefaultInstance()) return this;
      if (recipesBuilder_ == null) {
        if (!other.recipes_.isEmpty()) {
          if (recipes_.isEmpty()) {
            recipes_ = other.recipes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecipesIsMutable();
            recipes_.addAll(other.recipes_);
          }
          onChanged();
        }
      } else {
        if (!other.recipes_.isEmpty()) {
          if (recipesBuilder_.isEmpty()) {
            recipesBuilder_.dispose();
            recipesBuilder_ = null;
            recipes_ = other.recipes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recipesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecipesFieldBuilder() : null;
          } else {
            recipesBuilder_.addAllMessages(other.recipes_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.recipes.api.GetRecipesByAuthorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.recipes.api.GetRecipesByAuthorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.recipes.model.Recipe> recipes_ =
      java.util.Collections.emptyList();
    private void ensureRecipesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recipes_ = new java.util.ArrayList<com.recipes.model.Recipe>(recipes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.recipes.model.Recipe, com.recipes.model.Recipe.Builder, com.recipes.model.RecipeOrBuilder> recipesBuilder_;

    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public java.util.List<com.recipes.model.Recipe> getRecipesList() {
      if (recipesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recipes_);
      } else {
        return recipesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public int getRecipesCount() {
      if (recipesBuilder_ == null) {
        return recipes_.size();
      } else {
        return recipesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public com.recipes.model.Recipe getRecipes(int index) {
      if (recipesBuilder_ == null) {
        return recipes_.get(index);
      } else {
        return recipesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder setRecipes(
        int index, com.recipes.model.Recipe value) {
      if (recipesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipesIsMutable();
        recipes_.set(index, value);
        onChanged();
      } else {
        recipesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder setRecipes(
        int index, com.recipes.model.Recipe.Builder builderForValue) {
      if (recipesBuilder_ == null) {
        ensureRecipesIsMutable();
        recipes_.set(index, builderForValue.build());
        onChanged();
      } else {
        recipesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder addRecipes(com.recipes.model.Recipe value) {
      if (recipesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipesIsMutable();
        recipes_.add(value);
        onChanged();
      } else {
        recipesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder addRecipes(
        int index, com.recipes.model.Recipe value) {
      if (recipesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipesIsMutable();
        recipes_.add(index, value);
        onChanged();
      } else {
        recipesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder addRecipes(
        com.recipes.model.Recipe.Builder builderForValue) {
      if (recipesBuilder_ == null) {
        ensureRecipesIsMutable();
        recipes_.add(builderForValue.build());
        onChanged();
      } else {
        recipesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder addRecipes(
        int index, com.recipes.model.Recipe.Builder builderForValue) {
      if (recipesBuilder_ == null) {
        ensureRecipesIsMutable();
        recipes_.add(index, builderForValue.build());
        onChanged();
      } else {
        recipesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder addAllRecipes(
        java.lang.Iterable<? extends com.recipes.model.Recipe> values) {
      if (recipesBuilder_ == null) {
        ensureRecipesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recipes_);
        onChanged();
      } else {
        recipesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder clearRecipes() {
      if (recipesBuilder_ == null) {
        recipes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recipesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public Builder removeRecipes(int index) {
      if (recipesBuilder_ == null) {
        ensureRecipesIsMutable();
        recipes_.remove(index);
        onChanged();
      } else {
        recipesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public com.recipes.model.Recipe.Builder getRecipesBuilder(
        int index) {
      return getRecipesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public com.recipes.model.RecipeOrBuilder getRecipesOrBuilder(
        int index) {
      if (recipesBuilder_ == null) {
        return recipes_.get(index);  } else {
        return recipesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public java.util.List<? extends com.recipes.model.RecipeOrBuilder> 
         getRecipesOrBuilderList() {
      if (recipesBuilder_ != null) {
        return recipesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recipes_);
      }
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public com.recipes.model.Recipe.Builder addRecipesBuilder() {
      return getRecipesFieldBuilder().addBuilder(
          com.recipes.model.Recipe.getDefaultInstance());
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public com.recipes.model.Recipe.Builder addRecipesBuilder(
        int index) {
      return getRecipesFieldBuilder().addBuilder(
          index, com.recipes.model.Recipe.getDefaultInstance());
    }
    /**
     * <code>repeated .model.v1.Recipe recipes = 1 [json_name = "recipes"];</code>
     */
    public java.util.List<com.recipes.model.Recipe.Builder> 
         getRecipesBuilderList() {
      return getRecipesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.recipes.model.Recipe, com.recipes.model.Recipe.Builder, com.recipes.model.RecipeOrBuilder> 
        getRecipesFieldBuilder() {
      if (recipesBuilder_ == null) {
        recipesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.recipes.model.Recipe, com.recipes.model.Recipe.Builder, com.recipes.model.RecipeOrBuilder>(
                recipes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recipes_ = null;
      }
      return recipesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.v1.GetRecipesByAuthorResponse)
  }

  // @@protoc_insertion_point(class_scope:api.v1.GetRecipesByAuthorResponse)
  private static final com.recipes.api.GetRecipesByAuthorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.recipes.api.GetRecipesByAuthorResponse();
  }

  public static com.recipes.api.GetRecipesByAuthorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRecipesByAuthorResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRecipesByAuthorResponse>() {
    @java.lang.Override
    public GetRecipesByAuthorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetRecipesByAuthorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetRecipesByAuthorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRecipesByAuthorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.recipes.api.GetRecipesByAuthorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

