// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1/recipes_api.proto

package com.recipes.api;

public interface GetRecipesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.GetRecipesRequest)
    com.google.protobuf.MessageOrBuilder {
}
