// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1/recipes_api.proto

package com.recipes.api;

public interface GetRecipesByAuthorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1.GetRecipesByAuthorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   * @return The author.
   */
  com.google.protobuf.StringValue getAuthor();
  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getAuthorOrBuilder();
}
