// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1/recipes_api.proto

package com.recipes.api;

/**
 * Protobuf type {@code api.v1.GetRecipesByAuthorRequest}
 */
public final class GetRecipesByAuthorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.v1.GetRecipesByAuthorRequest)
    GetRecipesByAuthorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRecipesByAuthorRequest.newBuilder() to construct.
  private GetRecipesByAuthorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRecipesByAuthorRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRecipesByAuthorRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetRecipesByAuthorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (author_ != null) {
              subBuilder = author_.toBuilder();
            }
            author_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(author_);
              author_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.recipes.api.GetRecipesByAuthorRequest.class, com.recipes.api.GetRecipesByAuthorRequest.Builder.class);
  }

  public static final int AUTHOR_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue author_;
  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return author_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   * @return The author.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getAuthor() {
    return author_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : author_;
  }
  /**
   * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getAuthorOrBuilder() {
    return getAuthor();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (author_ != null) {
      output.writeMessage(1, getAuthor());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (author_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAuthor());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.recipes.api.GetRecipesByAuthorRequest)) {
      return super.equals(obj);
    }
    com.recipes.api.GetRecipesByAuthorRequest other = (com.recipes.api.GetRecipesByAuthorRequest) obj;

    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.api.GetRecipesByAuthorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.recipes.api.GetRecipesByAuthorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v1.GetRecipesByAuthorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1.GetRecipesByAuthorRequest)
      com.recipes.api.GetRecipesByAuthorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.recipes.api.GetRecipesByAuthorRequest.class, com.recipes.api.GetRecipesByAuthorRequest.Builder.class);
    }

    // Construct using com.recipes.api.GetRecipesByAuthorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (authorBuilder_ == null) {
        author_ = null;
      } else {
        author_ = null;
        authorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.recipes.api.RecipesApi.internal_static_api_v1_GetRecipesByAuthorRequest_descriptor;
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorRequest getDefaultInstanceForType() {
      return com.recipes.api.GetRecipesByAuthorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorRequest build() {
      com.recipes.api.GetRecipesByAuthorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.recipes.api.GetRecipesByAuthorRequest buildPartial() {
      com.recipes.api.GetRecipesByAuthorRequest result = new com.recipes.api.GetRecipesByAuthorRequest(this);
      if (authorBuilder_ == null) {
        result.author_ = author_;
      } else {
        result.author_ = authorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.recipes.api.GetRecipesByAuthorRequest) {
        return mergeFrom((com.recipes.api.GetRecipesByAuthorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.recipes.api.GetRecipesByAuthorRequest other) {
      if (other == com.recipes.api.GetRecipesByAuthorRequest.getDefaultInstance()) return this;
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.recipes.api.GetRecipesByAuthorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.recipes.api.GetRecipesByAuthorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> authorBuilder_;
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return authorBuilder_ != null || author_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     * @return The author.
     */
    public com.google.protobuf.StringValue getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public Builder setAuthor(com.google.protobuf.StringValue value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
        onChanged();
      } else {
        authorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public Builder setAuthor(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
        onChanged();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public Builder mergeAuthor(com.google.protobuf.StringValue value) {
      if (authorBuilder_ == null) {
        if (author_ != null) {
          author_ =
            com.google.protobuf.StringValue.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }
        onChanged();
      } else {
        authorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public Builder clearAuthor() {
      if (authorBuilder_ == null) {
        author_ = null;
        onChanged();
      } else {
        author_ = null;
        authorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public com.google.protobuf.StringValue.Builder getAuthorBuilder() {
      
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue author = 1 [json_name = "author"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.v1.GetRecipesByAuthorRequest)
  }

  // @@protoc_insertion_point(class_scope:api.v1.GetRecipesByAuthorRequest)
  private static final com.recipes.api.GetRecipesByAuthorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.recipes.api.GetRecipesByAuthorRequest();
  }

  public static com.recipes.api.GetRecipesByAuthorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRecipesByAuthorRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetRecipesByAuthorRequest>() {
    @java.lang.Override
    public GetRecipesByAuthorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetRecipesByAuthorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetRecipesByAuthorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRecipesByAuthorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.recipes.api.GetRecipesByAuthorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

