// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1/recipes_api.proto

package com.recipes.api;

public final class RecipesApi {
  private RecipesApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_GetRecipesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1_GetRecipesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_GetRecipesByAuthorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1_GetRecipesByAuthorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_GetRecipesByAuthorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1_GetRecipesByAuthorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1_GetRecipesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1_GetRecipesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030api/v1/recipes_api.proto\022\006api.v1\032\036goog" +
      "le/protobuf/wrappers.proto\032\026model/v1/rec" +
      "ipes.proto\"@\n\022GetRecipesResponse\022*\n\007reci" +
      "pes\030\001 \003(\0132\020.model.v1.RecipeR\007recipes\"H\n\032" +
      "GetRecipesByAuthorResponse\022*\n\007recipes\030\001 " +
      "\003(\0132\020.model.v1.RecipeR\007recipes\"Q\n\031GetRec" +
      "ipesByAuthorRequest\0224\n\006author\030\001 \001(\0132\034.go" +
      "ogle.protobuf.StringValueR\006author\"\023\n\021Get" +
      "RecipesRequest2\263\001\n\017ProtoApiService\022C\n\nGe" +
      "tRecipes\022\031.api.v1.GetRecipesRequest\032\032.ap" +
      "i.v1.GetRecipesResponse\022[\n\022GetRecipesByA" +
      "uthor\022!.api.v1.GetRecipesByAuthorRequest" +
      "\032\".api.v1.GetRecipesByAuthorResponseB\035\n\017" +
      "com.recipes.apiP\001\312\002\007recipesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.recipes.model.Recipes.getDescriptor(),
        });
    internal_static_api_v1_GetRecipesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_v1_GetRecipesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1_GetRecipesResponse_descriptor,
        new java.lang.String[] { "Recipes", });
    internal_static_api_v1_GetRecipesByAuthorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_v1_GetRecipesByAuthorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1_GetRecipesByAuthorResponse_descriptor,
        new java.lang.String[] { "Recipes", });
    internal_static_api_v1_GetRecipesByAuthorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_v1_GetRecipesByAuthorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1_GetRecipesByAuthorRequest_descriptor,
        new java.lang.String[] { "Author", });
    internal_static_api_v1_GetRecipesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_v1_GetRecipesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1_GetRecipesRequest_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.recipes.model.Recipes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
