// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

/**
 * Protobuf type {@code model.v1.Ingredient}
 */
public final class Ingredient extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.v1.Ingredient)
    IngredientOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Ingredient.newBuilder() to construct.
  private Ingredient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Ingredient() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Ingredient();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Ingredient(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (amountCase_ == 2) {
              subBuilder = ((com.google.protobuf.StringValue) amount_).toBuilder();
            }
            amount_ =
                input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.StringValue) amount_);
              amount_ = subBuilder.buildPartial();
            }
            amountCase_ = 2;
            break;
          }
          case 26: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (amountCase_ == 3) {
              subBuilder = ((com.google.protobuf.DoubleValue) amount_).toBuilder();
            }
            amount_ =
                input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.DoubleValue) amount_);
              amount_ = subBuilder.buildPartial();
            }
            amountCase_ = 3;
            break;
          }
          case 34: {
            com.recipes.model.Unit.Builder subBuilder = null;
            if (unit_ != null) {
              subBuilder = unit_.toBuilder();
            }
            unit_ = input.readMessage(com.recipes.model.Unit.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(unit_);
              unit_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.recipes.model.Recipes.internal_static_model_v1_Ingredient_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.recipes.model.Recipes.internal_static_model_v1_Ingredient_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.recipes.model.Ingredient.class, com.recipes.model.Ingredient.Builder.class);
  }

  private int amountCase_ = 0;
  private java.lang.Object amount_;
  public enum AmountCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    VALUE(2),
    QUANTITY(3),
    AMOUNT_NOT_SET(0);
    private final int value;
    private AmountCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AmountCase valueOf(int value) {
      return forNumber(value);
    }

    public static AmountCase forNumber(int value) {
      switch (value) {
        case 2: return VALUE;
        case 3: return QUANTITY;
        case 0: return AMOUNT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public AmountCase
  getAmountCase() {
    return AmountCase.forNumber(
        amountCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue name_;
  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getName() {
    return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
  }
  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  /**
   * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return amountCase_ == 2;
  }
  /**
   * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getValue() {
    if (amountCase_ == 2) {
       return (com.google.protobuf.StringValue) amount_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getValueOrBuilder() {
    if (amountCase_ == 2) {
       return (com.google.protobuf.StringValue) amount_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }

  public static final int QUANTITY_FIELD_NUMBER = 3;
  /**
   * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return amountCase_ == 3;
  }
  /**
   * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
   * @return The quantity.
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValue getQuantity() {
    if (amountCase_ == 3) {
       return (com.google.protobuf.DoubleValue) amount_;
    }
    return com.google.protobuf.DoubleValue.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.DoubleValueOrBuilder getQuantityOrBuilder() {
    if (amountCase_ == 3) {
       return (com.google.protobuf.DoubleValue) amount_;
    }
    return com.google.protobuf.DoubleValue.getDefaultInstance();
  }

  public static final int UNIT_FIELD_NUMBER = 4;
  private com.recipes.model.Unit unit_;
  /**
   * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
   * @return Whether the unit field is set.
   */
  @java.lang.Override
  public boolean hasUnit() {
    return unit_ != null;
  }
  /**
   * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
   * @return The unit.
   */
  @java.lang.Override
  public com.recipes.model.Unit getUnit() {
    return unit_ == null ? com.recipes.model.Unit.getDefaultInstance() : unit_;
  }
  /**
   * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
   */
  @java.lang.Override
  public com.recipes.model.UnitOrBuilder getUnitOrBuilder() {
    return getUnit();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (name_ != null) {
      output.writeMessage(1, getName());
    }
    if (amountCase_ == 2) {
      output.writeMessage(2, (com.google.protobuf.StringValue) amount_);
    }
    if (amountCase_ == 3) {
      output.writeMessage(3, (com.google.protobuf.DoubleValue) amount_);
    }
    if (unit_ != null) {
      output.writeMessage(4, getUnit());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getName());
    }
    if (amountCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.google.protobuf.StringValue) amount_);
    }
    if (amountCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.protobuf.DoubleValue) amount_);
    }
    if (unit_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUnit());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.recipes.model.Ingredient)) {
      return super.equals(obj);
    }
    com.recipes.model.Ingredient other = (com.recipes.model.Ingredient) obj;

    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasUnit() != other.hasUnit()) return false;
    if (hasUnit()) {
      if (!getUnit()
          .equals(other.getUnit())) return false;
    }
    if (!getAmountCase().equals(other.getAmountCase())) return false;
    switch (amountCase_) {
      case 2:
        if (!getValue()
            .equals(other.getValue())) return false;
        break;
      case 3:
        if (!getQuantity()
            .equals(other.getQuantity())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasUnit()) {
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
    }
    switch (amountCase_) {
      case 2:
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        break;
      case 3:
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.recipes.model.Ingredient parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Ingredient parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Ingredient parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Ingredient parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Ingredient parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Ingredient parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Ingredient parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.model.Ingredient parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.model.Ingredient parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.recipes.model.Ingredient parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.model.Ingredient parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.model.Ingredient parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.recipes.model.Ingredient prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.v1.Ingredient}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.v1.Ingredient)
      com.recipes.model.IngredientOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.recipes.model.Recipes.internal_static_model_v1_Ingredient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.recipes.model.Recipes.internal_static_model_v1_Ingredient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.recipes.model.Ingredient.class, com.recipes.model.Ingredient.Builder.class);
    }

    // Construct using com.recipes.model.Ingredient.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (unitBuilder_ == null) {
        unit_ = null;
      } else {
        unit_ = null;
        unitBuilder_ = null;
      }
      amountCase_ = 0;
      amount_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.recipes.model.Recipes.internal_static_model_v1_Ingredient_descriptor;
    }

    @java.lang.Override
    public com.recipes.model.Ingredient getDefaultInstanceForType() {
      return com.recipes.model.Ingredient.getDefaultInstance();
    }

    @java.lang.Override
    public com.recipes.model.Ingredient build() {
      com.recipes.model.Ingredient result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.recipes.model.Ingredient buildPartial() {
      com.recipes.model.Ingredient result = new com.recipes.model.Ingredient(this);
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (amountCase_ == 2) {
        if (valueBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = valueBuilder_.build();
        }
      }
      if (amountCase_ == 3) {
        if (quantityBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = quantityBuilder_.build();
        }
      }
      if (unitBuilder_ == null) {
        result.unit_ = unit_;
      } else {
        result.unit_ = unitBuilder_.build();
      }
      result.amountCase_ = amountCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.recipes.model.Ingredient) {
        return mergeFrom((com.recipes.model.Ingredient)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.recipes.model.Ingredient other) {
      if (other == com.recipes.model.Ingredient.getDefaultInstance()) return this;
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasUnit()) {
        mergeUnit(other.getUnit());
      }
      switch (other.getAmountCase()) {
        case VALUE: {
          mergeValue(other.getValue());
          break;
        }
        case QUANTITY: {
          mergeQuantity(other.getQuantity());
          break;
        }
        case AMOUNT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.recipes.model.Ingredient parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.recipes.model.Ingredient) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int amountCase_ = 0;
    private java.lang.Object amount_;
    public AmountCase
        getAmountCase() {
      return AmountCase.forNumber(
          amountCase_);
    }

    public Builder clearAmount() {
      amountCase_ = 0;
      amount_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.StringValue name_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public com.google.protobuf.StringValue getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public Builder setName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public Builder setName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public Builder mergeName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public com.google.protobuf.StringValue.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> valueBuilder_;
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return amountCase_ == 2;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getValue() {
      if (valueBuilder_ == null) {
        if (amountCase_ == 2) {
          return (com.google.protobuf.StringValue) amount_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      } else {
        if (amountCase_ == 2) {
          return valueBuilder_.getMessage();
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    public Builder setValue(com.google.protobuf.StringValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        amount_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }
      amountCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    public Builder setValue(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        amount_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      amountCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    public Builder mergeValue(com.google.protobuf.StringValue value) {
      if (valueBuilder_ == null) {
        if (amountCase_ == 2 &&
            amount_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          amount_ = com.google.protobuf.StringValue.newBuilder((com.google.protobuf.StringValue) amount_)
              .mergeFrom(value).buildPartial();
        } else {
          amount_ = value;
        }
        onChanged();
      } else {
        if (amountCase_ == 2) {
          valueBuilder_.mergeFrom(value);
        }
        valueBuilder_.setMessage(value);
      }
      amountCase_ = 2;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        if (amountCase_ == 2) {
          amountCase_ = 0;
          amount_ = null;
          onChanged();
        }
      } else {
        if (amountCase_ == 2) {
          amountCase_ = 0;
          amount_ = null;
        }
        valueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    public com.google.protobuf.StringValue.Builder getValueBuilder() {
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getValueOrBuilder() {
      if ((amountCase_ == 2) && (valueBuilder_ != null)) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        if (amountCase_ == 2) {
          return (com.google.protobuf.StringValue) amount_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.StringValue value = 2 [json_name = "value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        if (!(amountCase_ == 2)) {
          amount_ = com.google.protobuf.StringValue.getDefaultInstance();
        }
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                (com.google.protobuf.StringValue) amount_,
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      amountCase_ = 2;
      onChanged();;
      return valueBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> quantityBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return amountCase_ == 3;
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     * @return The quantity.
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValue getQuantity() {
      if (quantityBuilder_ == null) {
        if (amountCase_ == 3) {
          return (com.google.protobuf.DoubleValue) amount_;
        }
        return com.google.protobuf.DoubleValue.getDefaultInstance();
      } else {
        if (amountCase_ == 3) {
          return quantityBuilder_.getMessage();
        }
        return com.google.protobuf.DoubleValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    public Builder setQuantity(com.google.protobuf.DoubleValue value) {
      if (quantityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        amount_ = value;
        onChanged();
      } else {
        quantityBuilder_.setMessage(value);
      }
      amountCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    public Builder setQuantity(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (quantityBuilder_ == null) {
        amount_ = builderForValue.build();
        onChanged();
      } else {
        quantityBuilder_.setMessage(builderForValue.build());
      }
      amountCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    public Builder mergeQuantity(com.google.protobuf.DoubleValue value) {
      if (quantityBuilder_ == null) {
        if (amountCase_ == 3 &&
            amount_ != com.google.protobuf.DoubleValue.getDefaultInstance()) {
          amount_ = com.google.protobuf.DoubleValue.newBuilder((com.google.protobuf.DoubleValue) amount_)
              .mergeFrom(value).buildPartial();
        } else {
          amount_ = value;
        }
        onChanged();
      } else {
        if (amountCase_ == 3) {
          quantityBuilder_.mergeFrom(value);
        }
        quantityBuilder_.setMessage(value);
      }
      amountCase_ = 3;
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    public Builder clearQuantity() {
      if (quantityBuilder_ == null) {
        if (amountCase_ == 3) {
          amountCase_ = 0;
          amount_ = null;
          onChanged();
        }
      } else {
        if (amountCase_ == 3) {
          amountCase_ = 0;
          amount_ = null;
        }
        quantityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    public com.google.protobuf.DoubleValue.Builder getQuantityBuilder() {
      return getQuantityFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.DoubleValueOrBuilder getQuantityOrBuilder() {
      if ((amountCase_ == 3) && (quantityBuilder_ != null)) {
        return quantityBuilder_.getMessageOrBuilder();
      } else {
        if (amountCase_ == 3) {
          return (com.google.protobuf.DoubleValue) amount_;
        }
        return com.google.protobuf.DoubleValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue quantity = 3 [json_name = "quantity"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getQuantityFieldBuilder() {
      if (quantityBuilder_ == null) {
        if (!(amountCase_ == 3)) {
          amount_ = com.google.protobuf.DoubleValue.getDefaultInstance();
        }
        quantityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                (com.google.protobuf.DoubleValue) amount_,
                getParentForChildren(),
                isClean());
        amount_ = null;
      }
      amountCase_ = 3;
      onChanged();;
      return quantityBuilder_;
    }

    private com.recipes.model.Unit unit_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.recipes.model.Unit, com.recipes.model.Unit.Builder, com.recipes.model.UnitOrBuilder> unitBuilder_;
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     * @return Whether the unit field is set.
     */
    public boolean hasUnit() {
      return unitBuilder_ != null || unit_ != null;
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     * @return The unit.
     */
    public com.recipes.model.Unit getUnit() {
      if (unitBuilder_ == null) {
        return unit_ == null ? com.recipes.model.Unit.getDefaultInstance() : unit_;
      } else {
        return unitBuilder_.getMessage();
      }
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public Builder setUnit(com.recipes.model.Unit value) {
      if (unitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unit_ = value;
        onChanged();
      } else {
        unitBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public Builder setUnit(
        com.recipes.model.Unit.Builder builderForValue) {
      if (unitBuilder_ == null) {
        unit_ = builderForValue.build();
        onChanged();
      } else {
        unitBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public Builder mergeUnit(com.recipes.model.Unit value) {
      if (unitBuilder_ == null) {
        if (unit_ != null) {
          unit_ =
            com.recipes.model.Unit.newBuilder(unit_).mergeFrom(value).buildPartial();
        } else {
          unit_ = value;
        }
        onChanged();
      } else {
        unitBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public Builder clearUnit() {
      if (unitBuilder_ == null) {
        unit_ = null;
        onChanged();
      } else {
        unit_ = null;
        unitBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public com.recipes.model.Unit.Builder getUnitBuilder() {
      
      onChanged();
      return getUnitFieldBuilder().getBuilder();
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    public com.recipes.model.UnitOrBuilder getUnitOrBuilder() {
      if (unitBuilder_ != null) {
        return unitBuilder_.getMessageOrBuilder();
      } else {
        return unit_ == null ?
            com.recipes.model.Unit.getDefaultInstance() : unit_;
      }
    }
    /**
     * <code>.model.v1.Unit unit = 4 [json_name = "unit"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.recipes.model.Unit, com.recipes.model.Unit.Builder, com.recipes.model.UnitOrBuilder> 
        getUnitFieldBuilder() {
      if (unitBuilder_ == null) {
        unitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.recipes.model.Unit, com.recipes.model.Unit.Builder, com.recipes.model.UnitOrBuilder>(
                getUnit(),
                getParentForChildren(),
                isClean());
        unit_ = null;
      }
      return unitBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.v1.Ingredient)
  }

  // @@protoc_insertion_point(class_scope:model.v1.Ingredient)
  private static final com.recipes.model.Ingredient DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.recipes.model.Ingredient();
  }

  public static com.recipes.model.Ingredient getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ingredient>
      PARSER = new com.google.protobuf.AbstractParser<Ingredient>() {
    @java.lang.Override
    public Ingredient parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Ingredient(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Ingredient> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ingredient> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.recipes.model.Ingredient getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

