// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

public interface RecipeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.v1.Recipe)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 1 [json_name = "name"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
   * @return The author.
   */
  com.google.protobuf.StringValue getAuthor();
  /**
   * <code>.google.protobuf.StringValue author = 2 [json_name = "author"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getAuthorOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 3 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updated_at = 4 [json_name = "updatedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

  /**
   * <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
   * @return The description.
   */
  com.google.protobuf.StringValue getDescription();
  /**
   * <code>.google.protobuf.StringValue description = 5 [json_name = "description"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
   * @return Whether the prepTime field is set.
   */
  boolean hasPrepTime();
  /**
   * <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
   * @return The prepTime.
   */
  com.google.protobuf.Int32Value getPrepTime();
  /**
   * <code>.google.protobuf.Int32Value prep_time = 6 [json_name = "prepTime"];</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getPrepTimeOrBuilder();

  /**
   * <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
   * @return Whether the cookTime field is set.
   */
  boolean hasCookTime();
  /**
   * <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
   * @return The cookTime.
   */
  com.google.protobuf.UInt32Value getCookTime();
  /**
   * <code>.google.protobuf.UInt32Value cook_time = 7 [json_name = "cookTime"];</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getCookTimeOrBuilder();

  /**
   * <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
   * @return Whether the servings field is set.
   */
  boolean hasServings();
  /**
   * <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
   * @return The servings.
   */
  com.google.protobuf.UInt32Value getServings();
  /**
   * <code>.google.protobuf.UInt32Value servings = 8 [json_name = "servings"];</code>
   */
  com.google.protobuf.UInt32ValueOrBuilder getServingsOrBuilder();

  /**
   * <code>.model.v1.Difficulty difficulty = 9 [json_name = "difficulty"];</code>
   * @return The enum numeric value on the wire for difficulty.
   */
  int getDifficultyValue();
  /**
   * <code>.model.v1.Difficulty difficulty = 9 [json_name = "difficulty"];</code>
   * @return The difficulty.
   */
  com.recipes.model.Difficulty getDifficulty();

  /**
   * <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
   */
  java.util.List<com.recipes.model.Ingredient> 
      getIngredientsList();
  /**
   * <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
   */
  com.recipes.model.Ingredient getIngredients(int index);
  /**
   * <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
   */
  int getIngredientsCount();
  /**
   * <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
   */
  java.util.List<? extends com.recipes.model.IngredientOrBuilder> 
      getIngredientsOrBuilderList();
  /**
   * <code>repeated .model.v1.Ingredient ingredients = 10 [json_name = "ingredients"];</code>
   */
  com.recipes.model.IngredientOrBuilder getIngredientsOrBuilder(
      int index);

  /**
   * <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
   */
  java.util.List<com.recipes.model.Step> 
      getStepsList();
  /**
   * <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
   */
  com.recipes.model.Step getSteps(int index);
  /**
   * <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
   */
  int getStepsCount();
  /**
   * <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
   */
  java.util.List<? extends com.recipes.model.StepOrBuilder> 
      getStepsOrBuilderList();
  /**
   * <code>repeated .model.v1.Step steps = 11 [json_name = "steps"];</code>
   */
  com.recipes.model.StepOrBuilder getStepsOrBuilder(
      int index);

  /**
   * <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
   */
  java.util.List<com.google.protobuf.BytesValue> 
      getImagesList();
  /**
   * <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
   */
  com.google.protobuf.BytesValue getImages(int index);
  /**
   * <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
   */
  int getImagesCount();
  /**
   * <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
   */
  java.util.List<? extends com.google.protobuf.BytesValueOrBuilder> 
      getImagesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.BytesValue images = 12 [json_name = "images"];</code>
   */
  com.google.protobuf.BytesValueOrBuilder getImagesOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
   * @return Whether the notes field is set.
   */
  boolean hasNotes();
  /**
   * <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
   * @return The notes.
   */
  com.google.protobuf.StringValue getNotes();
  /**
   * <code>.google.protobuf.StringValue notes = 13 [json_name = "notes"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getNotesOrBuilder();
}
