// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

public final class Recipes {
  private Recipes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_v1_Recipe_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_v1_Recipe_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_v1_Step_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_v1_Step_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_v1_Ingredient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_v1_Ingredient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_v1_Unit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_v1_Unit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026model/v1/recipes.proto\022\010model.v1\032\036goog" +
      "le/protobuf/wrappers.proto\032\037google/proto" +
      "buf/timestamp.proto\"\322\005\n\006Recipe\0220\n\004name\030\001" +
      " \001(\0132\034.google.protobuf.StringValueR\004name" +
      "\0224\n\006author\030\002 \001(\0132\034.google.protobuf.Strin" +
      "gValueR\006author\0229\n\ncreated_at\030\003 \001(\0132\032.goo" +
      "gle.protobuf.TimestampR\tcreatedAt\0229\n\nupd" +
      "ated_at\030\004 \001(\0132\032.google.protobuf.Timestam" +
      "pR\tupdatedAt\022>\n\013description\030\005 \001(\0132\034.goog" +
      "le.protobuf.StringValueR\013description\0228\n\t" +
      "prep_time\030\006 \001(\0132\033.google.protobuf.Int32V" +
      "alueR\010prepTime\0229\n\tcook_time\030\007 \001(\0132\034.goog" +
      "le.protobuf.UInt32ValueR\010cookTime\0228\n\010ser" +
      "vings\030\010 \001(\0132\034.google.protobuf.UInt32Valu" +
      "eR\010servings\0224\n\ndifficulty\030\t \001(\0162\024.model." +
      "v1.DifficultyR\ndifficulty\0226\n\013ingredients" +
      "\030\n \003(\0132\024.model.v1.IngredientR\013ingredient" +
      "s\022$\n\005steps\030\013 \003(\0132\016.model.v1.StepR\005steps\022" +
      "3\n\006images\030\014 \003(\0132\033.google.protobuf.BytesV" +
      "alueR\006images\0222\n\005notes\030\r \001(\0132\034.google.pro" +
      "tobuf.StringValueR\005notes\"F\n\004Step\022>\n\013desc" +
      "ription\030\001 \001(\0132\034.google.protobuf.StringVa" +
      "lueR\013description\"\336\001\n\nIngredient\0220\n\004name\030" +
      "\001 \001(\0132\034.google.protobuf.StringValueR\004nam" +
      "e\0224\n\005value\030\002 \001(\0132\034.google.protobuf.Strin" +
      "gValueH\000R\005value\022:\n\010quantity\030\003 \001(\0132\034.goog" +
      "le.protobuf.DoubleValueH\000R\010quantity\022\"\n\004u" +
      "nit\030\004 \001(\0132\016.model.v1.UnitR\004unitB\010\n\006amoun" +
      "t\"\374\002\n\004Unit\0220\n\003uom\030\001 \001(\0132\034.google.protobu" +
      "f.StringValueH\000R\003uom\022F\n\017unit_of_measure\030" +
      "\002 \001(\0162\034.model.v1.Unit.UnitOfMeasureH\000R\ru" +
      "nitOfMeasure\"\351\001\n\rUnitOfMeasure\022$\n UNIT_O" +
      "F_MEASURE_UNIT_UNSPECIFIED\020\000\022\034\n\030UNIT_OF_" +
      "MEASURE_TEASPOON\020\001\022\036\n\032UNIT_OF_MEASURE_TA" +
      "BLESPOON\020\002\022\031\n\025UNIT_OF_MEASURE_GRAMS\020\003\022\035\n" +
      "\031UNIT_OF_MEASURE_KILOGRAMS\020\004\022\037\n\033UNIT_OF_" +
      "MEASURE_MILLILITERS\020\005\022\031\n\025UNIT_OF_MEASURE" +
      "_LITER\020\006B\016\n\014measure_unit*\\\n\nDifficulty\022\037" +
      "\n\033DIFFICULTY_EASY_UNSPECIFIED\020\000\022\030\n\024DIFFI" +
      "CULTY_MODERATED\020\001\022\023\n\017DIFFICULTY_HARD\020\002B\037" +
      "\n\021com.recipes.modelP\001\312\002\007recipesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_model_v1_Recipe_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_v1_Recipe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_v1_Recipe_descriptor,
        new java.lang.String[] { "Name", "Author", "CreatedAt", "UpdatedAt", "Description", "PrepTime", "CookTime", "Servings", "Difficulty", "Ingredients", "Steps", "Images", "Notes", });
    internal_static_model_v1_Step_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_v1_Step_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_v1_Step_descriptor,
        new java.lang.String[] { "Description", });
    internal_static_model_v1_Ingredient_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_v1_Ingredient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_v1_Ingredient_descriptor,
        new java.lang.String[] { "Name", "Value", "Quantity", "Unit", "Amount", });
    internal_static_model_v1_Unit_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_model_v1_Unit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_v1_Unit_descriptor,
        new java.lang.String[] { "Uom", "UnitOfMeasure", "MeasureUnit", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
