// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

public interface StepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.v1.Step)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue description = 1 [json_name = "description"];</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>.google.protobuf.StringValue description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  com.google.protobuf.StringValue getDescription();
  /**
   * <code>.google.protobuf.StringValue description = 1 [json_name = "description"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();
}
