// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

/**
 * Protobuf type {@code model.v1.Unit}
 */
public final class Unit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.v1.Unit)
    UnitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Unit.newBuilder() to construct.
  private Unit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Unit() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Unit();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Unit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (measureUnitCase_ == 1) {
              subBuilder = ((com.google.protobuf.StringValue) measureUnit_).toBuilder();
            }
            measureUnit_ =
                input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.protobuf.StringValue) measureUnit_);
              measureUnit_ = subBuilder.buildPartial();
            }
            measureUnitCase_ = 1;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            measureUnitCase_ = 2;
            measureUnit_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.recipes.model.Recipes.internal_static_model_v1_Unit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.recipes.model.Recipes.internal_static_model_v1_Unit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.recipes.model.Unit.class, com.recipes.model.Unit.Builder.class);
  }

  /**
   * Protobuf enum {@code model.v1.Unit.UnitOfMeasure}
   */
  public enum UnitOfMeasure
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNIT_OF_MEASURE_UNIT_UNSPECIFIED = 0;</code>
     */
    UNIT_OF_MEASURE_UNIT_UNSPECIFIED(0),
    /**
     * <code>UNIT_OF_MEASURE_TEASPOON = 1;</code>
     */
    UNIT_OF_MEASURE_TEASPOON(1),
    /**
     * <code>UNIT_OF_MEASURE_TABLESPOON = 2;</code>
     */
    UNIT_OF_MEASURE_TABLESPOON(2),
    /**
     * <code>UNIT_OF_MEASURE_GRAMS = 3;</code>
     */
    UNIT_OF_MEASURE_GRAMS(3),
    /**
     * <code>UNIT_OF_MEASURE_KILOGRAMS = 4;</code>
     */
    UNIT_OF_MEASURE_KILOGRAMS(4),
    /**
     * <code>UNIT_OF_MEASURE_MILLILITERS = 5;</code>
     */
    UNIT_OF_MEASURE_MILLILITERS(5),
    /**
     * <code>UNIT_OF_MEASURE_LITER = 6;</code>
     */
    UNIT_OF_MEASURE_LITER(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNIT_OF_MEASURE_UNIT_UNSPECIFIED = 0;</code>
     */
    public static final int UNIT_OF_MEASURE_UNIT_UNSPECIFIED_VALUE = 0;
    /**
     * <code>UNIT_OF_MEASURE_TEASPOON = 1;</code>
     */
    public static final int UNIT_OF_MEASURE_TEASPOON_VALUE = 1;
    /**
     * <code>UNIT_OF_MEASURE_TABLESPOON = 2;</code>
     */
    public static final int UNIT_OF_MEASURE_TABLESPOON_VALUE = 2;
    /**
     * <code>UNIT_OF_MEASURE_GRAMS = 3;</code>
     */
    public static final int UNIT_OF_MEASURE_GRAMS_VALUE = 3;
    /**
     * <code>UNIT_OF_MEASURE_KILOGRAMS = 4;</code>
     */
    public static final int UNIT_OF_MEASURE_KILOGRAMS_VALUE = 4;
    /**
     * <code>UNIT_OF_MEASURE_MILLILITERS = 5;</code>
     */
    public static final int UNIT_OF_MEASURE_MILLILITERS_VALUE = 5;
    /**
     * <code>UNIT_OF_MEASURE_LITER = 6;</code>
     */
    public static final int UNIT_OF_MEASURE_LITER_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UnitOfMeasure valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UnitOfMeasure forNumber(int value) {
      switch (value) {
        case 0: return UNIT_OF_MEASURE_UNIT_UNSPECIFIED;
        case 1: return UNIT_OF_MEASURE_TEASPOON;
        case 2: return UNIT_OF_MEASURE_TABLESPOON;
        case 3: return UNIT_OF_MEASURE_GRAMS;
        case 4: return UNIT_OF_MEASURE_KILOGRAMS;
        case 5: return UNIT_OF_MEASURE_MILLILITERS;
        case 6: return UNIT_OF_MEASURE_LITER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UnitOfMeasure>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UnitOfMeasure> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UnitOfMeasure>() {
            public UnitOfMeasure findValueByNumber(int number) {
              return UnitOfMeasure.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.recipes.model.Unit.getDescriptor().getEnumTypes().get(0);
    }

    private static final UnitOfMeasure[] VALUES = values();

    public static UnitOfMeasure valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UnitOfMeasure(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:model.v1.Unit.UnitOfMeasure)
  }

  private int measureUnitCase_ = 0;
  private java.lang.Object measureUnit_;
  public enum MeasureUnitCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UOM(1),
    UNIT_OF_MEASURE(2),
    MEASUREUNIT_NOT_SET(0);
    private final int value;
    private MeasureUnitCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MeasureUnitCase valueOf(int value) {
      return forNumber(value);
    }

    public static MeasureUnitCase forNumber(int value) {
      switch (value) {
        case 1: return UOM;
        case 2: return UNIT_OF_MEASURE;
        case 0: return MEASUREUNIT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MeasureUnitCase
  getMeasureUnitCase() {
    return MeasureUnitCase.forNumber(
        measureUnitCase_);
  }

  public static final int UOM_FIELD_NUMBER = 1;
  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   * @return Whether the uom field is set.
   */
  @java.lang.Override
  public boolean hasUom() {
    return measureUnitCase_ == 1;
  }
  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   * @return The uom.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getUom() {
    if (measureUnitCase_ == 1) {
       return (com.google.protobuf.StringValue) measureUnit_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getUomOrBuilder() {
    if (measureUnitCase_ == 1) {
       return (com.google.protobuf.StringValue) measureUnit_;
    }
    return com.google.protobuf.StringValue.getDefaultInstance();
  }

  public static final int UNIT_OF_MEASURE_FIELD_NUMBER = 2;
  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return Whether the unitOfMeasure field is set.
   */
  public boolean hasUnitOfMeasure() {
    return measureUnitCase_ == 2;
  }
  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return The enum numeric value on the wire for unitOfMeasure.
   */
  public int getUnitOfMeasureValue() {
    if (measureUnitCase_ == 2) {
      return (java.lang.Integer) measureUnit_;
    }
    return 0;
  }
  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return The unitOfMeasure.
   */
  public com.recipes.model.Unit.UnitOfMeasure getUnitOfMeasure() {
    if (measureUnitCase_ == 2) {
      @SuppressWarnings("deprecation")
      com.recipes.model.Unit.UnitOfMeasure result = com.recipes.model.Unit.UnitOfMeasure.valueOf(
          (java.lang.Integer) measureUnit_);
      return result == null ? com.recipes.model.Unit.UnitOfMeasure.UNRECOGNIZED : result;
    }
    return com.recipes.model.Unit.UnitOfMeasure.UNIT_OF_MEASURE_UNIT_UNSPECIFIED;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (measureUnitCase_ == 1) {
      output.writeMessage(1, (com.google.protobuf.StringValue) measureUnit_);
    }
    if (measureUnitCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) measureUnit_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (measureUnitCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.google.protobuf.StringValue) measureUnit_);
    }
    if (measureUnitCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) measureUnit_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.recipes.model.Unit)) {
      return super.equals(obj);
    }
    com.recipes.model.Unit other = (com.recipes.model.Unit) obj;

    if (!getMeasureUnitCase().equals(other.getMeasureUnitCase())) return false;
    switch (measureUnitCase_) {
      case 1:
        if (!getUom()
            .equals(other.getUom())) return false;
        break;
      case 2:
        if (getUnitOfMeasureValue()
            != other.getUnitOfMeasureValue()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (measureUnitCase_) {
      case 1:
        hash = (37 * hash) + UOM_FIELD_NUMBER;
        hash = (53 * hash) + getUom().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UNIT_OF_MEASURE_FIELD_NUMBER;
        hash = (53 * hash) + getUnitOfMeasureValue();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.recipes.model.Unit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Unit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Unit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Unit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Unit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.recipes.model.Unit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.recipes.model.Unit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.model.Unit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.model.Unit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.recipes.model.Unit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.recipes.model.Unit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.recipes.model.Unit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.recipes.model.Unit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.v1.Unit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.v1.Unit)
      com.recipes.model.UnitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.recipes.model.Recipes.internal_static_model_v1_Unit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.recipes.model.Recipes.internal_static_model_v1_Unit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.recipes.model.Unit.class, com.recipes.model.Unit.Builder.class);
    }

    // Construct using com.recipes.model.Unit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      measureUnitCase_ = 0;
      measureUnit_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.recipes.model.Recipes.internal_static_model_v1_Unit_descriptor;
    }

    @java.lang.Override
    public com.recipes.model.Unit getDefaultInstanceForType() {
      return com.recipes.model.Unit.getDefaultInstance();
    }

    @java.lang.Override
    public com.recipes.model.Unit build() {
      com.recipes.model.Unit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.recipes.model.Unit buildPartial() {
      com.recipes.model.Unit result = new com.recipes.model.Unit(this);
      if (measureUnitCase_ == 1) {
        if (uomBuilder_ == null) {
          result.measureUnit_ = measureUnit_;
        } else {
          result.measureUnit_ = uomBuilder_.build();
        }
      }
      if (measureUnitCase_ == 2) {
        result.measureUnit_ = measureUnit_;
      }
      result.measureUnitCase_ = measureUnitCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.recipes.model.Unit) {
        return mergeFrom((com.recipes.model.Unit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.recipes.model.Unit other) {
      if (other == com.recipes.model.Unit.getDefaultInstance()) return this;
      switch (other.getMeasureUnitCase()) {
        case UOM: {
          mergeUom(other.getUom());
          break;
        }
        case UNIT_OF_MEASURE: {
          setUnitOfMeasureValue(other.getUnitOfMeasureValue());
          break;
        }
        case MEASUREUNIT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.recipes.model.Unit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.recipes.model.Unit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int measureUnitCase_ = 0;
    private java.lang.Object measureUnit_;
    public MeasureUnitCase
        getMeasureUnitCase() {
      return MeasureUnitCase.forNumber(
          measureUnitCase_);
    }

    public Builder clearMeasureUnit() {
      measureUnitCase_ = 0;
      measureUnit_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> uomBuilder_;
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @return Whether the uom field is set.
     */
    @java.lang.Override
    public boolean hasUom() {
      return measureUnitCase_ == 1;
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     * @return The uom.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getUom() {
      if (uomBuilder_ == null) {
        if (measureUnitCase_ == 1) {
          return (com.google.protobuf.StringValue) measureUnit_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      } else {
        if (measureUnitCase_ == 1) {
          return uomBuilder_.getMessage();
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    public Builder setUom(com.google.protobuf.StringValue value) {
      if (uomBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        measureUnit_ = value;
        onChanged();
      } else {
        uomBuilder_.setMessage(value);
      }
      measureUnitCase_ = 1;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    public Builder setUom(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (uomBuilder_ == null) {
        measureUnit_ = builderForValue.build();
        onChanged();
      } else {
        uomBuilder_.setMessage(builderForValue.build());
      }
      measureUnitCase_ = 1;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    public Builder mergeUom(com.google.protobuf.StringValue value) {
      if (uomBuilder_ == null) {
        if (measureUnitCase_ == 1 &&
            measureUnit_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          measureUnit_ = com.google.protobuf.StringValue.newBuilder((com.google.protobuf.StringValue) measureUnit_)
              .mergeFrom(value).buildPartial();
        } else {
          measureUnit_ = value;
        }
        onChanged();
      } else {
        if (measureUnitCase_ == 1) {
          uomBuilder_.mergeFrom(value);
        }
        uomBuilder_.setMessage(value);
      }
      measureUnitCase_ = 1;
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    public Builder clearUom() {
      if (uomBuilder_ == null) {
        if (measureUnitCase_ == 1) {
          measureUnitCase_ = 0;
          measureUnit_ = null;
          onChanged();
        }
      } else {
        if (measureUnitCase_ == 1) {
          measureUnitCase_ = 0;
          measureUnit_ = null;
        }
        uomBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    public com.google.protobuf.StringValue.Builder getUomBuilder() {
      return getUomFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getUomOrBuilder() {
      if ((measureUnitCase_ == 1) && (uomBuilder_ != null)) {
        return uomBuilder_.getMessageOrBuilder();
      } else {
        if (measureUnitCase_ == 1) {
          return (com.google.protobuf.StringValue) measureUnit_;
        }
        return com.google.protobuf.StringValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getUomFieldBuilder() {
      if (uomBuilder_ == null) {
        if (!(measureUnitCase_ == 1)) {
          measureUnit_ = com.google.protobuf.StringValue.getDefaultInstance();
        }
        uomBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                (com.google.protobuf.StringValue) measureUnit_,
                getParentForChildren(),
                isClean());
        measureUnit_ = null;
      }
      measureUnitCase_ = 1;
      onChanged();;
      return uomBuilder_;
    }

    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @return Whether the unitOfMeasure field is set.
     */
    @java.lang.Override
    public boolean hasUnitOfMeasure() {
      return measureUnitCase_ == 2;
    }
    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @return The enum numeric value on the wire for unitOfMeasure.
     */
    @java.lang.Override
    public int getUnitOfMeasureValue() {
      if (measureUnitCase_ == 2) {
        return ((java.lang.Integer) measureUnit_).intValue();
      }
      return 0;
    }
    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @param value The enum numeric value on the wire for unitOfMeasure to set.
     * @return This builder for chaining.
     */
    public Builder setUnitOfMeasureValue(int value) {
      measureUnitCase_ = 2;
      measureUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @return The unitOfMeasure.
     */
    @java.lang.Override
    public com.recipes.model.Unit.UnitOfMeasure getUnitOfMeasure() {
      if (measureUnitCase_ == 2) {
        @SuppressWarnings("deprecation")
        com.recipes.model.Unit.UnitOfMeasure result = com.recipes.model.Unit.UnitOfMeasure.valueOf(
            (java.lang.Integer) measureUnit_);
        return result == null ? com.recipes.model.Unit.UnitOfMeasure.UNRECOGNIZED : result;
      }
      return com.recipes.model.Unit.UnitOfMeasure.UNIT_OF_MEASURE_UNIT_UNSPECIFIED;
    }
    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @param value The unitOfMeasure to set.
     * @return This builder for chaining.
     */
    public Builder setUnitOfMeasure(com.recipes.model.Unit.UnitOfMeasure value) {
      if (value == null) {
        throw new NullPointerException();
      }
      measureUnitCase_ = 2;
      measureUnit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitOfMeasure() {
      if (measureUnitCase_ == 2) {
        measureUnitCase_ = 0;
        measureUnit_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.v1.Unit)
  }

  // @@protoc_insertion_point(class_scope:model.v1.Unit)
  private static final com.recipes.model.Unit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.recipes.model.Unit();
  }

  public static com.recipes.model.Unit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Unit>
      PARSER = new com.google.protobuf.AbstractParser<Unit>() {
    @java.lang.Override
    public Unit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Unit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Unit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Unit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.recipes.model.Unit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

