// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/v1/recipes.proto

package com.recipes.model;

public interface UnitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.v1.Unit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   * @return Whether the uom field is set.
   */
  boolean hasUom();
  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   * @return The uom.
   */
  com.google.protobuf.StringValue getUom();
  /**
   * <code>.google.protobuf.StringValue uom = 1 [json_name = "uom"];</code>
   */
  com.google.protobuf.StringValueOrBuilder getUomOrBuilder();

  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return Whether the unitOfMeasure field is set.
   */
  boolean hasUnitOfMeasure();
  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return The enum numeric value on the wire for unitOfMeasure.
   */
  int getUnitOfMeasureValue();
  /**
   * <code>.model.v1.Unit.UnitOfMeasure unit_of_measure = 2 [json_name = "unitOfMeasure"];</code>
   * @return The unitOfMeasure.
   */
  com.recipes.model.Unit.UnitOfMeasure getUnitOfMeasure();

  public com.recipes.model.Unit.MeasureUnitCase getMeasureUnitCase();
}
